# Generated by Django 6.0.1 on 2026-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název 1'),
        ),
    ]
